{
  "global": {
    "scrape_interval": "15s",
    "evaluation_interval": "15s"
  },
  "alerting": {
    "alertmanagers": [
      {
        "static_configs": [
          {
            "targets": [
              "alertmanager:9093"
            ]
          }
        ]
      }
    ]
  },
  "rule_files": [
    "alert_rules.yml"
  ],
  "scrape_configs": [
    {
      "job_name": "prometheus",
      "static_configs": [
        {
          "targets": [
            "localhost:9090"
          ]
        }
      ]
    },
    {
      "job_name": "codesign-app",
      "kubernetes_sd_configs": [
        {
          "role": "pod",
          "namespaces": {
            "names": [
              "codesign-production"
            ]
          }
        }
      ],
      "relabel_configs": [
        {
          "source_labels": [
            "__meta_kubernetes_pod_label_app"
          ],
          "action": "keep",
          "regex": "codesign-app"
        },
        {
          "source_labels": [
            "__meta_kubernetes_pod_annotation_prometheus_io_scrape"
          ],
          "action": "keep",
          "regex": "true"
        }
      ]
    }
  ]
}