# Enhanced Dependabot configuration for AI Hardware Co-Design Playground
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "develop"
    open-pull-requests-limit: 5
    assignees:
      - "danieleschmidt"
    reviewers:
      - "danieleschmidt"
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "deps(python):"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tensorflow"
        update-types: ["version-update:semver-major"]
    groups:
      ml-frameworks:
        patterns:
          - "torch*"
          - "tensorflow*"
          - "onnx*"
          - "transformers"
          - "accelerate"
      testing:
        patterns:
          - "pytest*"
          - "hypothesis"
          - "factory-boy"
          - "freezegun"
          - "responses"
      code-quality:
        patterns:
          - "black"
          - "isort"
          - "ruff"
          - "mypy"
          - "pylint"
          - "bandit"
          - "safety"
      security:
        patterns:
          - "bandit"
          - "safety"
          - "cryptography"
          - "requests"
          - "urllib3"

  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    target-branch: "develop"
    open-pull-requests-limit: 5
    assignees:
      - "danieleschmidt"
    reviewers:
      - "danieleschmidt"
    labels:
      - "dependencies"
      - "nodejs"
      - "security"
    commit-message:
      prefix: "deps(nodejs):"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      build-tools:
        patterns:
          - "webpack*"
          - "babel*"
          - "eslint*"
          - "prettier"
          - "typescript"
      testing:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "cypress*"
          - "vitest*"
      security:
        patterns:
          - "helmet"
          - "cors"
          - "express-rate-limit"
          - "express-validator"

  # Frontend dependencies (if frontend directory exists)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "develop"
    open-pull-requests-limit: 3
    assignees:
      - "danieleschmidt"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "deps(frontend):"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "develop"
    open-pull-requests-limit: 3
    assignees:
      - "danieleschmidt"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    commit-message:
      prefix: "deps(docker):"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first-monday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "develop"
    open-pull-requests-limit: 5
    assignees:
      - "danieleschmidt"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
      - "security"
    commit-message:
      prefix: "deps(actions):"
      include: "scope"
    groups:
      actions:
        patterns:
          - "actions/*"
          - "github/*"
          - "codecov/*"
          - "docker/*"
          - "anchore/*"
          - "aquasecurity/*"